# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run.
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Enable src repos
        run: sudo sed -iE 's/^# deb-src/deb-src/' /etc/apt/sources.list && sudo apt-get update

      - name: Install dependencies
        run: sudo apt-get install build-essential gcc gdb binutils libmpfr6 libmpfr-dev libgmp-dev libgmp10 libmpc-dev libmpc3

      - name: Install build dependencies
        run: sudo apt-get build-dep gdb binutils

      - name: Cache sources
        uses: actions/cache@v2
        env:
          cache-name: cache-sources
        with:
          path: |
            *.tar.gz
            *.tar.bz2
            *.tar.xz
          key: build-${{ env.cache-name }}-${{ hashFiles('toolchain.sh') }}

      - name: Build toolchain
        run: ./toolchain.sh

      - name: upload build artifacts
        uses: actions/upload-artifact@v2.2.2
        with:
          # Artifact name
          #name: # optional, default is artifact
          # A file, directory or wildcard pattern that describes what to upload
          path: "build*"
          # The desired behavior if no files are found using the provided path.
          if-no-files-found: error
          # Duration after which artifact will expire in days. 0 means using default retention. Minimum 1 day. Maximum 90 days unless changed from the repository settings page.
          retention-days: 0
